services:
  - type: web
    name: portfolio-flask
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --preload --workers 2 --threads 8 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGODB_URI
        sync: false 